# Generated by Django 4.2.1 on 2024-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spanner',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='spanner',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='spanner',
            index=models.Index(fields=['-time_create'], name='spanner_spa_time_cr_722db4_idx'),
        ),
    ]
