# Generated by Django 4.2.1 on 2024-09-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spanner', '0005_category_spanner_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanner',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spanner.category'),
            preserve_default=False,
        ),
    ]
