# Generated by Django 4.2.1 on 2024-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanner', '0008_creator_spanner_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
